package core;
//*******1*********2*********3*********4*********5*********6*********7*********8

import java.util.ArrayList;

/**
 * A class representing a single PAW GAME
 * 
 * originally: * Generated by JasthiGUI.java for WordSearch
 * updated for PAW game
 * 
 */
public class Game
{

	private String id;
	private String title;
	private ArrayList<String> wordList;
	private ArrayList<ArrayList<String>> columnData; //size = # of columns

	private String[][] puzzleGrid;
	private int gridWidth; // derived
	private int gridHeight; // derived

	Game(String an_id, String a_title, ArrayList<String> a_word_list,
			ArrayList<ArrayList<String>> a_columnData)
	{
		id = an_id;
		title = a_title;
		wordList = a_word_list;
		columnData = a_columnData;
	}

	/**
	 * Set method for the variable id
	 */
	public void setId(String a_id)
	{
		id = a_id;
	}

	/**
	 * Get method for the variable id
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Set method for the variable title
	 */
	public void setTitle(String a_title)
	{
		title = a_title;
	}

	/**
	 * Get method for the variable title
	 */
	public String getTitle()
	{
		return title;
	}
	
	/**
	 * Set method for the variable wordList
	 */
	public void setWordList(ArrayList<String> a_word_list)
	{
		wordList = a_word_list;
	}
	
	/**
	 * Method for returning the word list
	 * 
	 * @return
	 */
	public ArrayList<String> getWordList()
	{
		return this.wordList;
	}
	
	/**
	 * Method for setting the column  Data
	 */
	public void setColumnData(ArrayList<ArrayList<String>> a_columnData){
		columnData = a_columnData;
	}
	
	/**
	 * Method for getting the column Data
	 */
	public ArrayList<ArrayList<String>> getColumnData(){
		return this.columnData;
	}
	
	/**
	 * Method to get Number of Columns in game
	 */
	public int getNumberColumns(){
		return columnData.size();
	}

	/**
	 * Method to get Number of Words in game
	 */
	public int getNumberWords(){
		return wordList.size();
	}

	/**
	 * Set method for the variable gridWidth
	 */
	public void setGridWidth(int a_grid_width)
	{
		gridWidth = a_grid_width;
	}

	/**
	 * Set method for the variable gridHeight
	 */
	public void setGridHeight(int a_grid_height)
	{
		gridHeight = a_grid_height;
	}

	/**
	 * Set method for the variable puzzleGrid
	 */
	public void setPuzzleGrid(String[][] a_puzzle_grid)
	{
		puzzleGrid = a_puzzle_grid;
	}

	/**
	 * Get method for the variable gridWidth
	 */
	public int getGridWidth()
	{
		return gridWidth;
	}

	/**
	 * Get method for the variable gridHeight
	 */
	public int getGridHeight()
	{
		return gridHeight;
	}

	/**
	 * Get method for the variable puzzleGrid
	 */
	public String[][] getPuzzleGrid()
	{
		return puzzleGrid;
	}

	/**
	 * Returns the String representation of Game object
	 */
	public String toString()
	{
		String temp = "\nid = " + id + "\ntitle = " + title;

		return temp;
	}

}
