package core;
//*******1*********2*********3*********4*********5*********6*********7*********8

import java.util.ArrayList;

/**
 * A class representing a single PAW GAME
 * 
 * originally: * Generated by JasthiGUI.java for WordSearch as a Puzzle
 * updated for PAW game as a Game
 * 
 */
public class Game
{

	private String id;
	private String title;
	private int level;
	private int wordLength;
	private boolean duplicate;
	private boolean charOrder;
	private int numberWords;
	private ArrayList<String> wordList;
	private ArrayList<ArrayList<String>> columnData; //size = # of columns/length of words

	public Game(int a_level, String a_title, ArrayList<String> a_word_list,
			ArrayList<ArrayList<String>> a_columnData, boolean a_dup, boolean a_order) {
		level = a_level;
		title = a_title;
		wordList = a_word_list;
		columnData = a_columnData;
		duplicate = a_dup;
		charOrder = a_order;
	}

	public Game(String an_id, int a_level, String a_title, ArrayList<String> a_word_list,
			ArrayList<ArrayList<String>> a_columnData, boolean a_dup, boolean a_order) {
		id = an_id;
		title = a_title;
		level = a_level;
		wordList = a_word_list;
		columnData = a_columnData;
		duplicate = a_dup;
		charOrder = a_order;
	}

	public Game() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * Set method for the variable id
	 */
	public void setId(String a_id)
	{
		id = a_id;
	}

	/**
	 * Get method for the variable id
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * returns the word length
	 */
	public int getWordLength(){
		return columnData.size();
	}
	
	/**
	 * Set method for the variable title
	 */
	public void setTitle(String a_title)
	{
		title = a_title;
	}

	/**
	 * Get method for the variable title
	 */
	public String getTitle()
	{
		return title;
	}
	
	/**
	 * Set method for the variable level
	 */
	public void setLevel(int a_level)
	{
		level = a_level;
	}
	
	/**
	 * Get method for the variable level
	 */
	public int getLevel()
	{
		return level;
	}
	
	/**
	 * set method for duplicate characters allowed
	 * true allows duplicate characters to display in single column
	 */
	public void setDuplicate(boolean b){
		duplicate = b;
	}
	
	/**
	 * get method for duplicate characters
	 */
	public boolean getDuplicate(){
		return duplicate;
	}

	/**
	 * set method for charOrder
	 * true indicates the columns are shuffle out of logical character order
	 */
	public void setCharOrder(boolean b){
		charOrder = b;
	}
	
	/**
	 * get method for duplicate characters
	 */
	public boolean getCharOrder(){
		return charOrder;
	}
	
	/**
	 * Set method for the variable wordList
	 */
	public void setWordList(ArrayList<String> a_word_list)
	{
		wordList = a_word_list;
	}
	
	/**
	 * Method for returning the word list
	 * 
	 * @return
	 */
	public ArrayList<String> getWordList()
	{
		return this.wordList;
	}
	
	/**
	 * Method for setting the column  Data
	 */
	public void setColumnData(ArrayList<ArrayList<String>> a_columnData){
		columnData = a_columnData;
	}
	
	/**
	 * Method for getting the column Data
	 */
	public ArrayList<ArrayList<String>> getColumnData(){
		return this.columnData;
	}
	
	/**
	 * Method to get Number of Columns in game
	 */
	public int getNumberColumns(){
		return columnData.size();
	}

	/**
	 * Method to set Number of Words in game
	 */
	public void setNumberWords(int a_num){
		numberWords = a_num;;
	}
	
	/**
	 * Method to get Number of Words in game
	 */
	public int getNumberWords(){
		return wordList.size();
	}

	/**
	 * Returns the String representation of Game object
	 */
	public String toString()
	{
		String temp = "\nid = " + id + "\ntitle = " + title 
				+ "\nduplicate - " + String.valueOf(duplicate) 
				+ " charOrder - "+ String.valueOf(charOrder) 
				+ "\nwordList" + wordList + "\ncolumnData" + columnData;

		return temp;
	}

}
